### PR TITLE
discord message size fixes

### LINKED ISSUE #239: Sending zero characters to discord panics with index out of range error
# What happens

Attempting to send zero characters to Discord causes a panic

# What's expected

Attempting to send zero characters to Discord doesn't cause a panic

# Demo

```go
package main

import (
    "fmt"
    "github.com/containrrr/shoutrrr"
    "os"
)

func main() {
    if len(os.Args) < 2 {
        fmt.Printf("Usage: %s <url>\n", os.Args[0])
        os.Exit(1)
    }

    url := os.Args[1]

    fmt.Println("Sending one byte")
    err := shoutrrr.Send(url, "A")
    if err != nil {
        fmt.Println(err)
    }

    fmt.Println("Sending zero bytes")
    err = shoutrrr.Send(url, "")
    if err != nil {
        fmt.Println(err)
    }

    fmt.Println("Done")
}
```

```plain
% go run shoutrrr_sendzeroorone.go $URL
Sending one byte
Sending zero bytes
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/containrrr/shoutrrr/pkg/services/discord.CreatePayloadFromItems({0xc0000fa0a0, 0x0, 0x7fb0860a7fff}, {0x71dcc4, 0x0}, {0x50d9ff, 0x7b00ab, 0x2488ff, 0xffc441, 0xd60510}, ...)
        /home/justin/go/pkg/mod/github.com/containrrr/shoutrrr@v0.5.3/pkg/services/discord/discord_json.go:68 +0x2c5
github.com/containrrr/shoutrrr/pkg/services/discord.(*Service).sendItems(0xc000212000, {0xc0000fa0a0, 0x0, 0x1}, 0xc0000dc300, 0x0)
        /home/justin/go/pkg/mod/github.com/containrrr/shoutrrr@v0.5.3/pkg/services/discord/discord.go:60 +0x1ef
github.com/containrrr/shoutrrr/pkg/services/discord.(*Service).Send(0xc000212000, {0x0, 0xc000051170}, 0x13)
        /home/justin/go/pkg/mod/github.com/containrrr/shoutrrr@v0.5.3/pkg/services/discord/discord.go:43 +0x165
github.com/containrrr/shoutrrr.Send({0x7ffeff1f5633, 0xc000010018}, {0x0, 0x0})
        /home/justin/go/pkg/mod/github.com/containrrr/shoutrrr@v0.5.3/shoutrrr.go:23 +0x9f
main.main()
        /home/justin/work/notify/shoutrrr_harness/shoutrrr_sendzeroorone.go:24 +0x1d8
exit status 2
```

# More info

This is a potential DoS vulnerability. If an attacker can cause a consumer of shoutrrr to attempt to send zero-byte Discord message, the consumer will panic, rendering the service unavailable. Without a published [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) I don't have a way of discretely reporting this. May I suggest you publish a policy :)

### LINKED ISSUE #240: Sending 2000, 4000 or 6000 characters to Discord panics in util.PartitionMessage (index out of range)
# What happens

Sending exactly 2000, 4000 or 6000 characters to Discord panics

# What should happen

Sending any number of characters to Discord should succeed

# Demo

```go
package main

import (
	"fmt"
	t "github.com/containrrr/shoutrrr/pkg/types"
	"strings"
)

// BEGIN taken from shoutrrr 0.5.3 util and discord packages

var limits = t.MessageLimit{
	ChunkSize:      2000,
	TotalChunkSize: 6000,
	ChunkCount:     10,
}

const maxSearchRunes = 100

// Min returns the smallest of a and b
func Min(a int, b int) int {
	if a < b {
		return a
	}
	return b
}

// PartitionMessage splits a string into chunks that is at most chunkSize runes, it will search the last distance runes
// for a whitespace to make the split appear nicer. It will keep adding chunks until it reaches maxCount chunks, or if
// the total amount of runes in the chunks reach maxTotal.
// The chunks are returned together with the number of omitted runes (that did not fit into the chunks)
func PartitionMessage(input string, limits t.MessageLimit, distance int) (items []t.MessageItem, omitted int) {
	runes := []rune(input)
	chunkOffset := 0
	maxTotal := Min(len(runes), limits.TotalChunkSize)
	maxCount := limits.ChunkCount - 1

	for i := 0; i < maxCount; i++ {
		// If no suitable split point is found, use the chunkSize
		chunkEnd := chunkOffset + limits.ChunkSize
		// ... and start next chunk directly after this one
		nextChunkStart := chunkEnd
		if chunkEnd > maxTotal {
			// The chunk is smaller than the limit, no need to search
			chunkEnd = maxTotal
			nextChunkStart = maxTotal
		} else {
			for r := 0; r < distance; r++ {
				rp := chunkEnd - r
				if runes[rp] == '\n' || runes[rp] == ' ' {
					// Suitable split point found
					chunkEnd = rp
					// Since the split is on a whitespace, skip it in the next chunk
					nextChunkStart = chunkEnd + 1
					break
				}
			}
		}

		items = append(items, t.MessageItem{
			Text: string(runes[chunkOffset:chunkEnd]),
		})

		chunkOffset = nextChunkStart
		if chunkOffset >= maxTotal {
			break
		}
	}

	return items, len(runes) - chunkOffset
}

// END taken from shoutrrr 0.5.3

func fuzz(length int) {
	defer func() {
		if r := recover(); r != nil {
			fmt.Printf("Recovered panic when partitioning message of length %d: %s\n", length, r)
		}
	}()
	PartitionMessage(strings.Repeat("A", length), limits, maxSearchRunes)
}

func main() {
	for i := 0; i <= 20000; i++ {
		fuzz(i)
	}
}

```

```plain
% go run shoutrrr_partitionmessage_fuzz.go
Recovered panic when partitioning message of length 2000: runtime error: index out of range [2000] with length 2000
Recovered panic when partitioning message of length 4000: runtime error: index out of range [4000] with length 4000
Recovered panic when partitioning message of length 6000: runtime error: index out of range [6000] with length 6000
```

# Notes

There is also a report of `util.PartitionMessage` panicking with what seems to be a message of 3990 characters - see https://github.com/projectdiscovery/notify/pull/130#pullrequestreview-979961409. I haven't been able to reproduce this crash. It may or may not be related.

This is a potential DoS vulnerability. If an attacker can cause a consumer of shoutrrr to attempt to send a Discord message of a precise length, the consumer will panic, rendering the service unavailable. Without a published [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) I don't have a way of discretely reporting this. May I suggest you publish a policy :)

### PR DESCRIPTION
**Pull request by piksel**
solves two panic conditions when using the discord service:
 - sending an empty message without a title 
    (fixes #239)
 - sending a message with partitioning and a message that is a modulus of the configured chunk size 
    (fixes #240)

### CODE REVIEW

File: pkg/services/discord/discord_json.go [hunk 1]
```diff
@@ -65,10 +70,14 @@ func CreatePayloadFromItems(items []types.MessageItem, title string, colors [typ
...
-	if omitted > 0 {
-		embeds[0].Footer = &embedFooter{
-			Text: fmt.Sprintf("... (%v character(s) where omitted)", omitted),
+	// This should not happen, but it's better to leave the index check before dereferencing the array
+	if len(embeds) > 0 {
+		embeds[0].Title = title
+
+		if omitted > 0 {
+			embeds[0].Footer = &embedFooter{
+				Text: fmt.Sprintf("... (%v character(s) where omitted)", omitted),
```
Comment (justinsteven) [inline pkg/services/discord/discord_json.go:79]: It's not related to this PR but there's a typo. where should be were.

**Comment by piksel** [comment]
@all-contributors add @justinsteven for bug
